"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import {
  DIMSCHEMA,
  LIM,
  SHORT,
  SIZES,
  SYSSUB,
  VENUES,
  compute,
  defaultAState,
  sizedDims,
  type AState,
  type DimField,
  type SysKey,
} from "@/app/(app)/design/quick/engine";
import { saveGridIntakeAction } from "./actions";

const fields: Array<{ key: SysKey; label: string }> = [
  { key: "audio", label: "Audio" }, { key: "video", label: "Video" },
  { key: "lighting", label: "Lighting" }, { key: "rigging", label: "Rigging" },
  { key: "curtains", label: "Curtains" }, { key: "controls", label: "Controls" },
  { key: "acoustical", label: "Acoustical" }, { key: "pit", label: "Pit filler" },
];

function initialState(value?: AState): AState {
  return value ? { ...value, sys: { ...value.sys } } : defaultAState(0);
}

export default function GridIntake({
  projectId,
  projectName,
  initialAutoConfig,
}: {
  projectId: string;
  projectName: string;
  initialAutoConfig?: AState;
}) {
  const router = useRouter();
  const [busy, startTransition] = useTransition();
  const [venueName, setVenueName] = useState("");
  const [locationName, setLocationName] = useState("");
  const [address, setAddress] = useState("");
  const [notes, setNotes] = useState("");
  const [measurementBased, setMeasurementBased] = useState(true);
  const [a, setA] = useState<AState>(() => initialState(initialAutoConfig));
  const [error, setError] = useState("");
  const venue = VENUES.find((v) => v.key === a.venue) || VENUES[0];
  const result = useMemo(() => compute(a), [a]);
  const update = (patch: Partial<AState>) => setA((current) => ({ ...current, ...patch }));
  const setVenue = (key: string) => {
    const next = VENUES.find((v) => v.key === key) || VENUES[0];
    update({ venue: next.key, sys: { ...next.sys }, ...sizedDims(next, a.size) });
  };
  const setDimension = (field: DimField, raw: string) => {
    const [min, max] = LIM[field];
    const value = Math.max(min, Math.min(max, Number(raw) || min));
    update({ [field]: value } as Partial<AState>);
  };
  const save = () => startTransition(async () => {
    const saved = await saveGridIntakeAction({ projectId, venueName, locationName, address, notes, measurementBased, autoConfig: a });
    if (!saved.ok) setError(saved.error);
    else router.refresh();
  });
  const input = { width: "100%", boxSizing: "border-box" as const, border: "1px solid #e4e7ec", borderRadius: 8, padding: "10px 11px", fontFamily: "var(--font-ui)", fontSize: 13, color: "#16181d", background: "#fff" };
  const section = { borderTop: "1px solid #ececf0", paddingTop: 18, marginTop: 20 };
  const label = { display: "block", fontSize: 10, fontWeight: 700, color: "#737985", textTransform: "uppercase" as const, marginBottom: 7, letterSpacing: ".06em" };
  return <div style={{ minHeight: "100%", background: "#f7f8fa", padding: "42px 22px" }}>
    <div style={{ maxWidth: 960, margin: "0 auto" }}>
      <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: ".08em", textTransform: "uppercase", color: "var(--accent)" }}>Design · Manual Layout intake</div>
      <h1 style={{ margin: "10px 0 8px", fontSize: 30, letterSpacing: "-.025em" }}>{projectName}</h1>
      <p style={{ margin: 0, color: "#737985", fontSize: 14, lineHeight: 1.55, maxWidth: 700 }}>Start with the same autogenerated design brief used by Design, then continue into the manual layout workspace. Venue details and measurements stay with this design.</p>
      <div style={{ marginTop: 26, background: "#fff", border: "1px solid #ececf0", borderRadius: 14, padding: 22, boxShadow: "0 1px 2px rgba(0,0,0,.04)" }}>
        <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1fr) minmax(0,1fr)", gap: 22 }}>
          <div>
            <div style={label}>Venue type</div>
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8 }}>
              {VENUES.map((item) => <button key={item.key} type="button" onClick={() => setVenue(item.key)} style={{ textAlign: "left", padding: "10px 11px", borderRadius: 9, cursor: "pointer", background: item.key === a.venue ? "color-mix(in srgb, var(--accent) 12%, #fff)" : "#fff", border: `1.5px solid ${item.key === a.venue ? "var(--accent)" : "#e8eaee"}` }}><span style={{ display: "block", fontSize: 13, fontWeight: 650 }}>{item.label}</span><span style={{ display: "block", color: "#9aa0ab", fontSize: 11, marginTop: 2 }}>{item.sub}</span></button>)}
            </div>
            <div style={{ ...section }}><div style={label}>Size of venue</div><div style={{ display: "flex", gap: 8 }}>{SIZES.map(([key, text]) => <button key={key} type="button" onClick={() => update({ size: key })} style={{ flex: 1, padding: "10px 8px", borderRadius: 9, cursor: "pointer", background: key === a.size ? "color-mix(in srgb, var(--accent) 12%, #fff)" : "#fff", border: `1.5px solid ${key === a.size ? "var(--accent)" : "#e8eaee"}`, fontWeight: 600 }}>{text}</button>)}</div></div>
            <div style={section}><div style={label}>Stage dimensions</div><div style={{ display: "grid", gap: 13 }}>{(DIMSCHEMA[venue.kind] || DIMSCHEMA.proscenium).map((d) => <label key={d.field}><span style={{ display: "flex", justifyContent: "space-between", fontSize: 12.5, fontWeight: 600 }}><span>{d.label}</span><span style={{ fontFamily: "var(--font-mono)", color: "#737985" }}>{a[d.field]} ft</span></span><span style={{ display: "block", color: "#9aa0ab", fontSize: 10.5, margin: "3px 0 5px" }}>{d.note}</span><input type="range" min={LIM[d.field][0]} max={LIM[d.field][1]} step={2} value={a[d.field]} onChange={(e) => setDimension(d.field, e.target.value)} style={{ width: "100%", accentColor: "var(--accent)" }} /></label>)}</div></div>
          </div>
          <div>
            <div style={label}>Systems to include</div>
            <div style={{ display: "grid", gap: 8 }}>{fields.map(({ key, label: name }) => { const on = !!a.sys[key]; return <button key={key} type="button" onClick={() => update({ sys: { ...a.sys, [key]: !on } })} style={{ display: "flex", alignItems: "center", justifyContent: "space-between", textAlign: "left", padding: "11px 12px", borderRadius: 9, cursor: "pointer", background: on ? "#fff" : "#f7f8fa", border: "1px solid #e8eaee" }}><span><span style={{ display: "block", fontSize: 13, fontWeight: 600 }}>{name}</span><span style={{ display: "block", color: "#9aa0ab", fontSize: 11 }}>{SYSSUB[key]}</span></span><span style={{ width: 34, height: 19, borderRadius: 999, background: on ? "var(--accent)" : "#d6d9e0", padding: 2, boxSizing: "border-box" }}><span style={{ display: "block", width: 15, height: 15, borderRadius: "50%", background: "#fff", marginLeft: on ? 15 : 0 }} /></span></button>; })}</div>
            <div style={section}><div style={label}>Starting tier</div><div style={{ display: "flex", gap: 8 }}>{(["good", "better", "best"] as const).map((tier) => <button key={tier} type="button" onClick={() => update({ tier })} style={{ flex: 1, padding: "10px 7px", borderRadius: 9, cursor: "pointer", background: a.tier === tier ? "color-mix(in srgb, var(--accent) 12%, #fff)" : "#fff", border: `1.5px solid ${a.tier === tier ? "var(--accent)" : "#e8eaee"}`, fontWeight: 600, textTransform: "capitalize" }}>{tier}</button>)}</div></div>
            <div style={{ ...section, background: "#fbf8fc", borderRadius: 10, padding: 14, borderTop: "none" }}><div style={label}>Autogenerated brief</div><div style={{ fontSize: 13, color: "#3a3f4a", lineHeight: 1.7 }}><div><strong>{result.systems.filter((s) => s.on).length}</strong> systems · <strong>{result.lineSets}</strong> line sets · <strong>{result.electrics}</strong> electrics</div><div style={{ color: "#737985" }}>{result.systems.filter((s) => s.on).map((s) => SHORT[s.key]).join(" · ") || "No systems selected"}</div></div></div>
          </div>
        </div>
        <div style={section}><div style={{ ...label, marginBottom: 12 }}>Venue cover page</div><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 14 }}><label><span style={label}>Location / campus</span><input value={locationName} onChange={e => setLocationName(e.target.value)} placeholder="High School" style={input} /></label><label><span style={label}>Venue / space</span><input value={venueName} onChange={e => setVenueName(e.target.value)} placeholder="Main space" style={input} /></label></div><label style={{ display: "block", marginTop: 14 }}><span style={label}>Address</span><input value={address} onChange={e => setAddress(e.target.value)} placeholder="Street, city, state" style={input} /></label><label style={{ display: "block", marginTop: 14 }}><span style={label}>Design notes</span><textarea value={notes} onChange={e => setNotes(e.target.value)} placeholder="Audience, stage, access, existing system notes…" style={{ ...input, minHeight: 78, resize: "vertical" }} /></label><label style={{ display: "flex", alignItems: "center", gap: 9, marginTop: 15, fontSize: 13, color: "#3a3f4a", cursor: "pointer" }}><input type="checkbox" checked={measurementBased} onChange={e => setMeasurementBased(e.target.checked)} /> Generate from measurements as I work</label></div>
        {error && <div style={{ marginTop: 12, color: "#b4543a", fontSize: 12 }}>{error}</div>}
        <button type="button" onClick={save} disabled={busy} style={{ marginTop: 22, width: "100%", border: "none", borderRadius: 9, padding: "12px 16px", background: "var(--accent)", color: "#fff", fontSize: 13.5, fontWeight: 700, cursor: busy ? "wait" : "pointer" }}>{busy ? "Saving…" : "Continue to Manual Layout →"}</button>
      </div>
    </div>
  </div>;
}
