-- Written idempotently ON PURPOSE. This migration was regenerated by
-- drizzle-kit when session/pensive-swift-b0f7 merged into main: it recreates,
-- as one migration, the objects that branch had added across its own
-- 0017_neat_killmonger … 0021_true_dark_phoenix. Those branch migrations were
-- ALREADY APPLIED to the Neon production database, because DATABASE_URL is
-- scoped to Production *and Preview* — every green preview build runs
-- scripts/migrate.mjs against the live database. drizzle's migrator picks work
-- by timestamp (pg-core/dialect.js: created_at < folderMillis), so this file's
-- later `when` makes it pending even though its DDL is already materialized,
-- and a plain CREATE TABLE fails with 42P07 — which is what broke the 45a7614
-- production deploy. IF NOT EXISTS makes the same DDL correct against both
-- that database and a fresh one (npm run db:reset-local, CI, a new Neon).
CREATE TABLE IF NOT EXISTS "grid_catalog" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "subassemblies" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sites" ADD COLUMN IF NOT EXISTS "location_name" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "last_login_at" bigint;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "previous_login_at" bigint;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "grid_catalog_seq_idx" ON "grid_catalog" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "grid_catalog_deleted_idx" ON "grid_catalog" USING btree ("deleted");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subassemblies_seq_idx" ON "subassemblies" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "subassemblies_deleted_idx" ON "subassemblies" USING btree ("deleted");--> statement-breakpoint
-- Hand-added, per the NOTE in 0012_seq_bump_trigger.sql: drizzle-kit does not
-- manage triggers, so regenerating these two tables from schema.ts silently
-- dropped the BEFORE UPDATE seq bumps the session branch created by hand
-- (0017_neat_killmonger, 0020_good_silhouette). Without them every UPDATE
-- leaves `seq` stale and pull-sync's `WHERE seq > cursor ORDER BY seq` stops
-- reporting the row — the exact failure 0012 and 0014 document. Postgres has
-- no CREATE TRIGGER IF NOT EXISTS, so drop-then-create keeps this rerunnable.
DROP TRIGGER IF EXISTS grid_catalog_seq_bump ON "grid_catalog";--> statement-breakpoint
CREATE TRIGGER grid_catalog_seq_bump BEFORE UPDATE ON "grid_catalog" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();--> statement-breakpoint
DROP TRIGGER IF EXISTS subassemblies_seq_bump ON "subassemblies";--> statement-breakpoint
CREATE TRIGGER subassemblies_seq_bump BEFORE UPDATE ON "subassemblies" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();
