-- Documents (#218, docs/superpowers/specs/2026-09-26-documents-design.md) —
-- company / venue / project files stored in private Vercel Blob and shared
-- both ways through the customer portal.
--
-- Generated by drizzle-kit, then hardened so it is idempotent per D141 (the
-- shared Neon database is migrated by more than one branch's build).
-- Column-for-column docTable(); the _seq_bump trigger keeps pull-sync's
-- `WHERE seq > cursor` honest.
CREATE TABLE IF NOT EXISTS "documents" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_seq_idx" ON "documents" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "documents_deleted_idx" ON "documents" USING btree ("deleted");--> statement-breakpoint
CREATE OR REPLACE TRIGGER documents_seq_bump BEFORE UPDATE ON "documents" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();
