-- Portal carts (#245 Task 8, spec 2026-09-27-portal-catalog-design.md) —
-- one cart per portal grant (id = grant id). NOT a quote row: no estimate
-- number is ever used here — a cart only ever becomes a quote through
-- Generate, which spawns a real quotes row.
--
-- Generated by drizzle-kit, then hardened so it is idempotent per D141 (the
-- shared Neon database is migrated by more than one branch's build).
-- Column-for-column docTable(); the _seq_bump trigger keeps pull-sync's
-- `WHERE seq > cursor` honest.
CREATE TABLE IF NOT EXISTS "portal_carts" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "portal_carts_seq_idx" ON "portal_carts" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "portal_carts_deleted_idx" ON "portal_carts" USING btree ("deleted");--> statement-breakpoint
CREATE OR REPLACE TRIGGER portal_carts_seq_bump BEFORE UPDATE ON "portal_carts" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();
