-- Customer Rewards ledger (#282 phase 2, spec
-- docs/superpowers/specs/2026-09-30-customer-rewards-design.md §4) —
-- append-only account-credit entries, one company each. Deterministic ids
-- (earn:<quoteId>:<n>, start:<companyId>, redeem:<quoteId>:<n>, …) make every
-- post idempotent. Wiped by the go-live demo reset (not a CONFIG collection);
-- never writable through sync push (not in SYNCABLE_COLLECTIONS).
--
-- Generated by drizzle-kit, then hardened so it is idempotent per D141 (the
-- shared Neon database is migrated by more than one branch's build).
-- Column-for-column docTable(); the _seq_bump trigger keeps pull-sync's
-- `WHERE seq > cursor` honest.
CREATE TABLE IF NOT EXISTS "reward_ledger" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reward_ledger_seq_idx" ON "reward_ledger" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "reward_ledger_deleted_idx" ON "reward_ledger" USING btree ("deleted");--> statement-breakpoint
CREATE OR REPLACE TRIGGER reward_ledger_seq_bump BEFORE UPDATE ON "reward_ledger" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();
