-- Manufacturers (Manufacturer section Part 1, spec
-- 2026-10-02-manufacturer-images-placeholders-design.md) — one record per
-- mfrKey holding the manufacturer's image (an unlinked part_documents image)
-- and, in later parts, vendor links and cost data.
--
-- Generated by drizzle-kit, then hardened so it is idempotent per D141 (the
-- shared Neon database is migrated by more than one branch's build).
-- Column-for-column docTable(); the _seq_bump trigger keeps pull-sync's
-- `WHERE seq > cursor` honest.
CREATE TABLE IF NOT EXISTS "manufacturers" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "manufacturers_seq_idx" ON "manufacturers" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "manufacturers_deleted_idx" ON "manufacturers" USING btree ("deleted");--> statement-breakpoint
CREATE OR REPLACE TRIGGER manufacturers_seq_bump BEFORE UPDATE ON "manufacturers" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();
