-- Address verification + drive time (spec
-- docs/superpowers/specs/2026-10-09-address-verification-drive-time-design.md):
-- four sites columns for the venue verification stamp and the place_book
-- table for every non-venue address. The one-time venue backfill runs in JS
-- (src/lib/address-verify/venue-geo.ts ensureVenueGeoStatus) because the
-- verified/needs_check rule (house number + usable point, state.ts
-- backfillStatus) is not expressible in SQL without drifting from it; until
-- it runs, readers fall back to the same rule.
--
-- Generated by drizzle-kit, then hardened so it is idempotent per D141 (the
-- shared Neon database is migrated by more than one branch's build).
-- Renumber at merge if another branch lands a 0036 first.
CREATE TABLE IF NOT EXISTS "place_book" (
	"key" text PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"lat" double precision,
	"lng" double precision,
	"status" text NOT NULL,
	"source" text NOT NULL,
	"verified_by" text,
	"verified_at" bigint,
	"updated_at" bigint NOT NULL
);
--> statement-breakpoint
ALTER TABLE "sites" ADD COLUMN IF NOT EXISTS "geo_status" text;--> statement-breakpoint
ALTER TABLE "sites" ADD COLUMN IF NOT EXISTS "geo_source" text;--> statement-breakpoint
ALTER TABLE "sites" ADD COLUMN IF NOT EXISTS "geo_verified_by" text;--> statement-breakpoint
ALTER TABLE "sites" ADD COLUMN IF NOT EXISTS "geo_verified_at" bigint;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "place_book_status_idx" ON "place_book" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sites_geo_status_idx" ON "sites" USING btree ("geo_status");
