-- Morning triage (spec docs/superpowers/specs/2026-10-09-morning-triage-design.md)
-- — triage_snapshots: one frozen ranked list per user per slot
-- (`<userId>:<YYYY-MM-DD>:<morning|midday>`); triage_marks: one Done /
-- Snooze / Dismiss mark per user per item (`<userId>:<itemKey>`).
--
-- Generated by drizzle-kit, then hardened so it is idempotent per D141 (the
-- shared Neon database is migrated by more than one branch's build).
-- Column-for-column docTable(); the _seq_bump trigger keeps pull-sync's
-- `WHERE seq > cursor` honest.
CREATE TABLE IF NOT EXISTS "triage_marks" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "triage_snapshots" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "triage_marks_seq_idx" ON "triage_marks" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "triage_marks_deleted_idx" ON "triage_marks" USING btree ("deleted");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "triage_snapshots_seq_idx" ON "triage_snapshots" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "triage_snapshots_deleted_idx" ON "triage_snapshots" USING btree ("deleted");--> statement-breakpoint
CREATE OR REPLACE TRIGGER triage_marks_seq_bump BEFORE UPDATE ON "triage_marks" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();--> statement-breakpoint
CREATE OR REPLACE TRIGGER triage_snapshots_seq_bump BEFORE UPDATE ON "triage_snapshots" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();
