-- #323 Krisp meeting matcher (docs/superpowers/specs/2026-10-09-krisp-meeting-matcher-design.md).
-- Generated by drizzle-kit, then hardened so it is idempotent per D141 (the shared Neon
-- database is migrated by more than one branch's build). Column-for-column docTable();
-- the _seq_bump trigger keeps pull-sync's `WHERE seq > cursor` honest.
CREATE TABLE IF NOT EXISTS "meetings" (
	"id" text PRIMARY KEY NOT NULL,
	"doc" jsonb NOT NULL,
	"rev" integer DEFAULT 1 NOT NULL,
	"seq" bigserial NOT NULL,
	"updated_at" bigint NOT NULL,
	"received_at" bigint NOT NULL,
	"review" jsonb,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
ALTER TABLE "krisp_connections" ADD COLUMN IF NOT EXISTS "meetings_synced_at" bigint;--> statement-breakpoint
ALTER TABLE "krisp_connections" ADD COLUMN IF NOT EXISTS "meetings_backfill_from" bigint;--> statement-breakpoint
ALTER TABLE "krisp_connections" ADD COLUMN IF NOT EXISTS "meetings_backfill_cursor" text;--> statement-breakpoint
ALTER TABLE "krisp_connections" ADD COLUMN IF NOT EXISTS "meetings_last_error" text;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meetings_seq_idx" ON "meetings" USING btree ("seq");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meetings_deleted_idx" ON "meetings" USING btree ("deleted");--> statement-breakpoint
CREATE OR REPLACE TRIGGER meetings_seq_bump BEFORE UPDATE ON "meetings" FOR EACH ROW EXECUTE FUNCTION bump_doc_seq();
