"use client";

import { CONDITION_CATEGORIES, CONDITION_RATINGS, EVENT_FREQUENCIES, EVENT_TYPES, GROWTH_GOALS, STAFF_TIERS, seedFindings, type AssessmentData } from "@/lib/stores/assessment";

export function AssessmentSection({ enabled, assessment, onEnabled, onChange }: { enabled: boolean; assessment: AssessmentData; onEnabled: (value: boolean) => void; onChange: (value: AssessmentData) => void }) {
  const patch = (fn: (a: AssessmentData) => AssessmentData) => onChange(fn(assessment));
  const toggle = (list: string[], value: string) => list.includes(value) ? list.filter((item) => item !== value) : list.concat(value);
  const findings = seedFindings(assessment);
  return <div>
    <label style={{ display: "flex", gap: 9, alignItems: "center", fontWeight: 600, cursor: "pointer" }}><input type="checkbox" checked={enabled} onChange={(e) => onEnabled(e.target.checked)} /> Add Condition &amp; Needs assessment</label>
    {enabled && <div style={{ marginTop: 16, display: "grid", gap: 18 }}>
      <p style={muted}>Use this when the customer has no defined ask or needs a formal advisory deliverable.</p>
      <div className="sv-grid"><Field label="Assessment date" value={assessment.date} onChange={(value) => patch((a) => ({ ...a, date: value }))} type="date" /><Field label="Assessors (comma-separated)" value={assessment.assessors.join(", ")} onChange={(value) => patch((a) => ({ ...a, assessors: value.split(",").map((x) => x.trim()).filter(Boolean) }))} /><Field label="Technical reviewer" value={assessment.technicalReviewer.name} onChange={(value) => patch((a) => ({ ...a, technicalReviewer: { ...a.technicalReviewer, name: value } }))} /><Field label="Reviewer role" value={assessment.technicalReviewer.role} onChange={(value) => patch((a) => ({ ...a, technicalReviewer: { ...a.technicalReviewer, role: value } }))} /></div>
      <Field label="Customer concern — in their own words" value={assessment.statedConcern} onChange={(value) => patch((a) => ({ ...a, statedConcern: value }))} textarea />
      <div><b>Usage profile</b><div style={chips}>{EVENT_TYPES.map((item) => <button key={item.key} style={chip(assessment.usage.eventTypes.some((x) => x.key === item.key))} onClick={() => patch((a) => ({ ...a, usage: { ...a.usage, eventTypes: a.usage.eventTypes.some((x) => x.key === item.key) ? a.usage.eventTypes.filter((x) => x.key !== item.key) : a.usage.eventTypes.concat({ key: item.key, frequency: "" }) } }))}>{item.label}</button>)}</div>{assessment.usage.eventTypes.map((item) => <div key={item.key} style={{ marginTop: 8 }}><label style={muted}>{EVENT_TYPES.find((x) => x.key === item.key)?.label} frequency </label><select value={item.frequency} onChange={(e) => patch((a) => ({ ...a, usage: { ...a.usage, eventTypes: a.usage.eventTypes.map((x) => x.key === item.key ? { ...x, frequency: e.target.value as typeof x.frequency } : x) } }))}>{EVENT_FREQUENCIES.map((x) => <option key={x.key} value={x.key}>{x.label}</option>)}</select></div>)}</div>
      <div className="sv-grid"><div><label style={muted}>Staff capability</label><select value={assessment.usage.staffTier} onChange={(e) => patch((a) => ({ ...a, usage: { ...a.usage, staffTier: e.target.value as typeof a.usage.staffTier } }))} style={control}><option value="" />{STAFF_TIERS.map((x) => <option key={x.key} value={x.key}>{x.label}</option>)}</select></div><Field label="Training gaps" value={assessment.usage.trainingGaps} onChange={(value) => patch((a) => ({ ...a, usage: { ...a.usage, trainingGaps: value } }))} /></div>
      <div><b>Growth goals</b><div style={chips}>{GROWTH_GOALS.map((item) => <button key={item} style={chip(assessment.usage.growthGoals.includes(item))} onClick={() => patch((a) => ({ ...a, usage: { ...a.usage, growthGoals: toggle(a.usage.growthGoals, item) } }))}>{item}</button>)}</div></div>
      <div><b>Condition ratings</b>{CONDITION_CATEGORIES.map((category) => { const value = assessment.conditions[category.key]; return <div key={category.key} style={{ display: "grid", gridTemplateColumns: "minmax(170px,1fr) minmax(240px,2fr)", gap: 10, alignItems: "center", padding: "10px 0", borderBottom: "1px solid #eef0f2" }}><span>{category.label}</span><div><div style={chips}>{CONDITION_RATINGS.map((rating) => <button key={rating.key} style={chip(value.rating === rating.key)} onClick={() => patch((a) => ({ ...a, conditions: { ...a.conditions, [category.key]: { ...a.conditions[category.key], rating: rating.key } } }))}>{rating.label}</button>)}</div><input value={value.notes} placeholder="Notes" onChange={(e) => patch((a) => ({ ...a, conditions: { ...a.conditions, [category.key]: { ...a.conditions[category.key], notes: e.target.value } } }))} style={{ ...control, marginTop: 7 }} /></div></div>; })}</div>
      <Field label="Electrical / power — contextual notes only. No condition rating; outside Peak’s lane." value={assessment.electricalNotes} onChange={(value) => patch((a) => ({ ...a, electricalNotes: value }))} textarea />
      <div><b>Findings &amp; recommendations</b>{assessment.findings.length === 0 && findings.seeded.length > 0 && <button style={button} onClick={() => patch((a) => ({ ...a, findings: findings.seeded }))}>Seed from ratings</button>}{assessment.findings.map((finding) => <div key={finding.id} style={{ marginTop: 9, padding: 10, border: "1px solid #e4e7ec", borderRadius: 9 }}><input value={finding.title} onChange={(e) => patch((a) => ({ ...a, findings: a.findings.map((f) => f.id === finding.id ? { ...f, title: e.target.value } : f) }))} style={control} /><textarea value={finding.detail} placeholder="Recommendation detail" onChange={(e) => patch((a) => ({ ...a, findings: a.findings.map((f) => f.id === finding.id ? { ...f, detail: e.target.value } : f) }))} style={{ ...control, marginTop: 7 }} /></div>)}{findings.unresolved.length > 0 && <p style={{ color: "#9a6700" }}>Unresolved ratings: {findings.unresolved.join(", ")}</p>}</div>
    </div>}
  </div>;
}
function Field({ label, value, onChange, textarea, type }: { label: string; value: string; onChange: (v: string) => void; textarea?: boolean; type?: string }) { return <label style={{ display: "grid", gap: 5, fontSize: 12, color: "#667085" }}>{label}{textarea ? <textarea value={value} onChange={(e) => onChange(e.target.value)} style={control} /> : <input type={type} value={value} onChange={(e) => onChange(e.target.value)} style={control} />}</label>; }
const control = { width: "100%", padding: "8px 9px", border: "1px solid #dfe3e8", borderRadius: 7, color: "#1f2937", background: "#fff" };
const muted = { fontSize: 12, color: "#667085", margin: 0 };
const chips = { display: "flex", gap: 6, flexWrap: "wrap" as const, marginTop: 7 };
const chip = (active: boolean) => ({ padding: "6px 9px", borderRadius: 16, border: `1px solid ${active ? "var(--accent)" : "#dfe3e8"}`, color: active ? "var(--accent)" : "#5b6470", background: active ? "color-mix(in srgb, var(--accent) 10%, white)" : "#fff", cursor: "pointer", fontSize: 12 });
const button = { display: "block", marginTop: 8, padding: "8px 10px", border: "1px solid var(--accent)", borderRadius: 8, background: "#fff", color: "var(--accent)", fontWeight: 600, cursor: "pointer" };
