"use client";

import { BUDGET_TIERS, CONDITION_CATEGORIES, CONDITION_RATINGS, EVENT_FREQUENCIES, EVENT_TYPES, FINDING_BUCKETS, GROWTH_GOALS, STAFF_TIERS, newFindingId, seedFindings, type AssessmentData, type ConditionCategory, type Finding, type InspectionRef } from "@/lib/stores/assessment";
import type { SurveyPhoto } from "@/lib/stores/surveys";

export function AssessmentSection({ enabled, assessment, photos, autoCerts = {}, onEnabled, onChange }: { enabled: boolean; assessment: AssessmentData; photos: SurveyPhoto[]; autoCerts?: Record<string, InspectionRef>; onEnabled: (value: boolean) => void; onChange: (value: AssessmentData) => void }) {
  const patch = (fn: (a: AssessmentData) => AssessmentData) => onChange(fn(assessment));
  const toggle = (list: string[], value: string) => list.includes(value) ? list.filter((item) => item !== value) : list.concat(value);
  const findings = seedFindings(assessment);
  return <div>
    <label style={{ display: "flex", gap: 9, alignItems: "center", fontWeight: 600, cursor: "pointer" }}><input type="checkbox" checked={enabled} onChange={(e) => onEnabled(e.target.checked)} /> Add Condition &amp; Needs assessment</label>
    {enabled && <div style={{ marginTop: 16, display: "grid", gap: 18 }}>
      <p style={muted}>Use this when the customer has no defined ask or needs a formal advisory deliverable.</p>
      <div className="sv-grid"><Field label="Assessment date" value={assessment.date} onChange={(value) => patch((a) => ({ ...a, date: value }))} type="date" /><Field label="Assessors (comma-separated)" value={assessment.assessors.join(", ")} onChange={(value) => patch((a) => ({ ...a, assessors: value.split(",").map((x) => x.trim()).filter(Boolean) }))} /><Field label="Technical reviewer" value={assessment.technicalReviewer.name} onChange={(value) => patch((a) => ({ ...a, technicalReviewer: { ...a.technicalReviewer, name: value } }))} /><Field label="Reviewer role" value={assessment.technicalReviewer.role} onChange={(value) => patch((a) => ({ ...a, technicalReviewer: { ...a.technicalReviewer, role: value } }))} /></div>
      <Field label="Customer concern — in their own words" value={assessment.statedConcern} onChange={(value) => patch((a) => ({ ...a, statedConcern: value }))} textarea />
      <div><b>Usage profile</b><div style={chips}>{EVENT_TYPES.map((item) => <button key={item.key} style={chip(assessment.usage.eventTypes.some((x) => x.key === item.key))} onClick={() => patch((a) => ({ ...a, usage: { ...a.usage, eventTypes: a.usage.eventTypes.some((x) => x.key === item.key) ? a.usage.eventTypes.filter((x) => x.key !== item.key) : a.usage.eventTypes.concat({ key: item.key, frequency: "" }) } }))}>{item.label}</button>)}</div>{assessment.usage.eventTypes.map((item) => <div key={item.key} style={{ marginTop: 8 }}><label style={muted}>{EVENT_TYPES.find((x) => x.key === item.key)?.label} frequency </label><select value={item.frequency} onChange={(e) => patch((a) => ({ ...a, usage: { ...a.usage, eventTypes: a.usage.eventTypes.map((x) => x.key === item.key ? { ...x, frequency: e.target.value as typeof x.frequency } : x) } }))}>{EVENT_FREQUENCIES.map((x) => <option key={x.key} value={x.key}>{x.label}</option>)}</select></div>)}</div>
      <div className="sv-grid"><div><label style={muted}>Staff capability</label><select value={assessment.usage.staffTier} onChange={(e) => patch((a) => ({ ...a, usage: { ...a.usage, staffTier: e.target.value as typeof a.usage.staffTier } }))} style={control}><option value="" />{STAFF_TIERS.map((x) => <option key={x.key} value={x.key}>{x.label}</option>)}</select></div><Field label="Training gaps" value={assessment.usage.trainingGaps} onChange={(value) => patch((a) => ({ ...a, usage: { ...a.usage, trainingGaps: value } }))} /></div>
      <div><b>Growth goals</b><div style={chips}>{GROWTH_GOALS.map((item) => <button key={item} style={chip(assessment.usage.growthGoals.includes(item))} onClick={() => patch((a) => ({ ...a, usage: { ...a.usage, growthGoals: toggle(a.usage.growthGoals, item) } }))}>{item}</button>)}</div><Field label="Growth notes" value={assessment.usage.growthNotes} onChange={(value) => patch((a) => ({ ...a, usage: { ...a.usage, growthNotes: value } }))} textarea /></div>
      <div><b>Condition ratings</b>{CONDITION_CATEGORIES.map((category) => { const value = assessment.conditions[category.key]; return <div key={category.key} style={{ display: "grid", gridTemplateColumns: "minmax(170px,1fr) minmax(240px,2fr)", gap: 10, alignItems: "center", padding: "10px 0", borderBottom: "1px solid #eef0f2" }}><span>{category.label}</span><div><div style={chips}>{CONDITION_RATINGS.map((rating) => <button key={rating.key} style={chip(value.rating === rating.key)} onClick={() => patch((a) => ({ ...a, conditions: { ...a.conditions, [category.key]: { ...a.conditions[category.key], rating: rating.key } } }))}>{rating.label}</button>)}</div><input value={value.notes} placeholder="Notes" onChange={(e) => patch((a) => ({ ...a, conditions: { ...a.conditions, [category.key]: { ...a.conditions[category.key], notes: e.target.value } } }))} style={{ ...control, marginTop: 7 }} /></div></div>; })}</div>
      <Field label="Electrical / power — contextual notes only. No condition rating; outside Peak’s lane." value={assessment.electricalNotes} onChange={(value) => patch((a) => ({ ...a, electricalNotes: value }))} textarea />
      <div><b>Formal inspection on file?</b><div className="sv-grid">{["rigging", "curtains", "lighting", "av"].map((key) => { const ref = assessment.inspectionRefs[key] || { onFile: "", type: "", date: "", source: "manual", recordId: null }; return <div key={key}><label style={muted}>{key}</label><div style={{ display: "flex", gap: 6 }}><select value={ref.onFile} onChange={(e) => patch((a) => ({ ...a, inspectionRefs: { ...a.inspectionRefs, [key]: { ...ref, onFile: e.target.value as "" | "yes" | "no", source: "manual" } } }))} style={control}><option value="" /> <option value="yes">Yes</option><option value="no">No</option></select><input placeholder="Type" value={ref.type} onChange={(e) => patch((a) => ({ ...a, inspectionRefs: { ...a.inspectionRefs, [key]: { ...ref, type: e.target.value, source: "manual" } } }))} style={control} /><input type="date" value={ref.date} onChange={(e) => patch((a) => ({ ...a, inspectionRefs: { ...a.inspectionRefs, [key]: { ...ref, date: e.target.value, source: "manual" } } }))} style={control} /></div></div>; })}</div></div>
      <div><b>Findings &amp; recommendations</b>{assessment.findings.length === 0 && findings.seeded.length > 0 && <button style={button} onClick={() => patch((a) => ({ ...a, findings: findings.seeded }))}>Seed from ratings</button>}<button style={button} onClick={() => patch((a) => ({ ...a, findings: a.findings.concat({ id: newFindingId(), categories: [], bucket: "", title: "", detail: "", budgetTier: "", photoIds: [] }) }))}>+ Add finding</button>{assessment.findings.map((finding) => <FindingEditor key={finding.id} finding={finding} photos={photos} onChange={(value) => patch((a) => ({ ...a, findings: a.findings.map((f) => f.id === value.id ? value : f) }))} onRemove={() => patch((a) => ({ ...a, findings: a.findings.filter((f) => f.id !== finding.id) }))} />)}{findings.unresolved.length > 0 && <p style={{ color: "#9a6700" }}>Unresolved ratings: {findings.unresolved.join(", ")}</p>}</div>
    </div>}
  </div>;
}
function FindingEditor({ finding, photos, onChange, onRemove }: { finding: Finding; photos: SurveyPhoto[]; onChange: (finding: Finding) => void; onRemove: () => void }) { const toggleCategory = (key: ConditionCategory) => onChange({ ...finding, categories: finding.categories.includes(key) ? finding.categories.filter((x) => x !== key) : finding.categories.concat(key) }); return <div style={{ marginTop: 9, padding: 10, border: "1px solid #e4e7ec", borderRadius: 9 }}><div style={{ display: "flex", gap: 7 }}><input value={finding.title} placeholder="Finding title" onChange={(e) => onChange({ ...finding, title: e.target.value })} style={control} /><button onClick={onRemove}>×</button></div><textarea value={finding.detail} placeholder="Recommendation detail" onChange={(e) => onChange({ ...finding, detail: e.target.value })} style={{ ...control, marginTop: 7 }} /><div style={chips}>{FINDING_BUCKETS.map((item) => <button key={item.key} style={chip(finding.bucket === item.key)} onClick={() => onChange({ ...finding, bucket: item.key })}>{item.label}</button>)}{BUDGET_TIERS.map((item) => <button key={item.key} style={chip(finding.budgetTier === item.key)} onClick={() => onChange({ ...finding, budgetTier: item.key })}>{item.label}</button>)}</div><div style={chips}>{CONDITION_CATEGORIES.map((item) => <button key={item.key} style={chip(finding.categories.includes(item.key))} onClick={() => toggleCategory(item.key)}>{item.label}</button>)}</div>{photos.length > 0 && <div style={chips}>{photos.map((photo) => <button key={photo.id} style={chip(finding.photoIds.includes(photo.id))} onClick={() => onChange({ ...finding, photoIds: finding.photoIds.includes(photo.id) ? finding.photoIds.filter((id) => id !== photo.id) : finding.photoIds.concat(photo.id) })}>Photo: {photo.name}</button>)}</div>}</div>; }
function Field({ label, value, onChange, textarea, type }: { label: string; value: string; onChange: (v: string) => void; textarea?: boolean; type?: string }) { return <label style={{ display: "grid", gap: 5, fontSize: 12, color: "#667085" }}>{label}{textarea ? <textarea value={value} onChange={(e) => onChange(e.target.value)} style={control} /> : <input type={type} value={value} onChange={(e) => onChange(e.target.value)} style={control} />}</label>; }
const control = { width: "100%", padding: "8px 9px", border: "1px solid #dfe3e8", borderRadius: 7, color: "#1f2937", background: "#fff" };
const muted = { fontSize: 12, color: "#667085", margin: 0 };
const chips = { display: "flex", gap: 6, flexWrap: "wrap" as const, marginTop: 7 };
const chip = (active: boolean) => ({ padding: "6px 9px", borderRadius: 16, border: `1px solid ${active ? "var(--accent)" : "#dfe3e8"}`, color: active ? "var(--accent)" : "#5b6470", background: active ? "color-mix(in srgb, var(--accent) 10%, white)" : "#fff", cursor: "pointer", fontSize: 12 });
const button = { display: "block", marginTop: 8, padding: "8px 10px", border: "1px solid var(--accent)", borderRadius: 8, background: "#fff", color: "var(--accent)", fontWeight: 600, cursor: "pointer" };
