/* ------------------------------------------------------------------ *
 * Grid stock symbols — the icon generator's logic (spec 2026-09-25 §3).
 * scripts/build-grid-icons.ts is the CLI; the spec harness imports this
 * module to prove the committed output is current and deterministic.
 * Reads @tabler/icons (a devDependency) from node_modules; the runtime
 * never does — it ships only src/lib/design/grid-icons.generated.ts.
 * ------------------------------------------------------------------ */
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

export type GridIconTag = "path" | "circle" | "rect" | "line" | "polyline" | "ellipse";
export type GridIconEl = { t: GridIconTag; a: Record<string, string>; fill?: true };
export type GridIconPick = { tabler: string; id: string; label: string; tags: string[] };
export type GeneratedIcon = { id: string; label: string; tags: string[]; tabler: string; els: GridIconEl[] };

/** Geometry attributes kept per element — everything else (class, stroke,
 *  stroke-width…) is dropped; the renderer owns presentation. */
const GEOMETRY: Record<GridIconTag, readonly string[]> = {
  path: ["d"],
  circle: ["cx", "cy", "r"],
  rect: ["x", "y", "width", "height", "rx", "ry"],
  line: ["x1", "y1", "x2", "y2"],
  polyline: ["points"],
  ellipse: ["cx", "cy", "rx", "ry"],
};

export const ICON_ID_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** Reduce one Tabler outline SVG to its drawable elements. Tabler's invisible
 *  24×24 bounding path (`stroke="none"`) is skipped; a `fill="currentColor"`
 *  element (a dot, a pin head) keeps `fill: true`. */
export function parseTablerSvg(svg: string): GridIconEl[] {
  const out: GridIconEl[] = [];
  for (const m of svg.matchAll(/<(path|circle|rect|line|polyline|ellipse)\b([^>]*?)\/?>/g)) {
    const tag = m[1] as GridIconTag;
    const attrs: Record<string, string> = {};
    for (const a of m[2].matchAll(/([a-zA-Z-]+)="([^"]*)"/g)) attrs[a[1]] = a[2];
    if (attrs.stroke === "none") continue;
    const a: Record<string, string> = {};
    for (const k of GEOMETRY[tag]) if (attrs[k] !== undefined) a[k] = attrs[k];
    if (!Object.keys(a).length) continue;
    out.push(attrs.fill === "currentColor" ? { t: tag, a, fill: true } : { t: tag, a });
  }
  return out;
}

/** Validate the hand-authored pick list: shape, id format, no duplicate id
 *  or Tabler name, no `shape-` ids (reserved for the legacy shapes). */
export function validatePicks(raw: unknown): GridIconPick[] {
  if (!Array.isArray(raw)) throw new Error("grid-icon-picks.json must be an array");
  const ids = new Set<string>();
  const names = new Set<string>();
  return raw.map((r, i) => {
    const p = r as Partial<GridIconPick>;
    if (typeof p.tabler !== "string" || typeof p.id !== "string" || typeof p.label !== "string" || !Array.isArray(p.tags)) {
      throw new Error(`pick ${i}: needs tabler, id, label, tags[]`);
    }
    if (!ICON_ID_RE.test(p.id) || p.id.startsWith("shape-")) throw new Error(`pick ${i}: bad id "${p.id}"`);
    if (ids.has(p.id)) throw new Error(`pick ${i}: duplicate id "${p.id}"`);
    if (names.has(p.tabler)) throw new Error(`pick ${i}: duplicate tabler name "${p.tabler}"`);
    ids.add(p.id);
    names.add(p.tabler);
    const tags = Array.from(new Set(p.tags.map((t) => String(t).trim().toLowerCase()).filter(Boolean)));
    return { tabler: p.tabler, id: p.id, label: p.label.trim(), tags };
  });
}

/** Resolve every pick against the package; throws naming EVERY missing one. */
export function buildIcons(picks: GridIconPick[], readSvg: (tabler: string) => string | null): GeneratedIcon[] {
  const missing: string[] = [];
  const icons: GeneratedIcon[] = [];
  for (const p of picks) {
    const svg = readSvg(p.tabler);
    if (svg === null) {
      missing.push(p.tabler);
      continue;
    }
    const els = parseTablerSvg(svg);
    if (!els.length) throw new Error(`${p.tabler}: no drawable elements`);
    icons.push({ id: p.id, label: p.label, tags: p.tags, tabler: p.tabler, els });
  }
  if (missing.length) throw new Error(`not in @tabler/icons outline set: ${missing.join(", ")}`);
  return icons.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
}

export function renderModule(icons: GeneratedIcon[], version: string): string {
  const rows = icons.map((i) => "  " + JSON.stringify({ id: i.id, label: i.label, tags: i.tags, tabler: i.tabler, els: i.els }) + ",");
  return [
    "// GENERATED by scripts/build-grid-icons.ts — do not edit by hand.",
    `// Source: @tabler/icons ${version} outline set (MIT, see LICENSES/tabler-icons.txt),`,
    "// filtered through the hand-authored pick list scripts/grid-icon-picks.json.",
    "// Regenerate: npm run icons:grid",
    "",
    'export type GridIconTag = "path" | "circle" | "rect" | "line" | "polyline" | "ellipse";',
    "export type GridIconEl = { t: GridIconTag; a: Record<string, string>; fill?: true };",
    "export type GeneratedGridIcon = { id: string; label: string; tags: string[]; tabler: string; els: GridIconEl[] };",
    "",
    `export const TABLER_ICONS_VERSION = ${JSON.stringify(version)};`,
    "",
    "export const GENERATED_GRID_ICONS: GeneratedGridIcon[] = [",
    ...rows,
    "];",
    "",
  ].join("\n");
}

export function renderLicense(licenseText: string, version: string): string {
  return [
    `Tabler Icons ${version} — https://tabler.io/icons — MIT License`,
    "Used for The Grid's stock device symbols. Only the curated outline icons listed in",
    "scripts/grid-icon-picks.json are copied (as path data) into src/lib/design/grid-icons.generated.ts.",
    "",
    "----------------------------------------------------------------------",
    "",
    licenseText.trim(),
    "",
  ].join("\n");
}

export const GENERATED_MODULE_PATH = "src/lib/design/grid-icons.generated.ts";
export const LICENSE_PATH = "LICENSES/tabler-icons.txt";
export const PICKS_PATH = "scripts/grid-icon-picks.json";

/** Everything the CLI writes, computed in memory from `root` (the repo). */
export function generateFromPackage(root: string): { module: string; license: string; count: number; version: string } {
  const pkgDir = path.join(root, "node_modules", "@tabler", "icons");
  if (!existsSync(path.join(pkgDir, "package.json"))) {
    throw new Error("@tabler/icons is not installed — run `npm ci` (it is a devDependency)");
  }
  const version = String(JSON.parse(readFileSync(path.join(pkgDir, "package.json"), "utf8")).version);
  const picks = validatePicks(JSON.parse(readFileSync(path.join(root, PICKS_PATH), "utf8")));
  const icons = buildIcons(picks, (name) => {
    const file = path.join(pkgDir, "icons", "outline", `${name}.svg`);
    return existsSync(file) ? readFileSync(file, "utf8") : null;
  });
  return {
    module: renderModule(icons, version),
    license: renderLicense(readFileSync(path.join(pkgDir, "LICENSE"), "utf8"), version),
    count: icons.length,
    version,
  };
}
