import type { SurveyDraft, SurveyRecord } from "@/lib/stores/surveys";
import { blankSystemsState } from "@/lib/stores/survey-intake";

/**
 * These fixtures are deliberately *pre*-Venue-Assessments (D132) documents:
 * they carry no venueClass / venueSubtype / visitPurpose / linesets /
 * assessment, exactly like every record written before that change. The
 * read-time migration in surveys.ts normalize() supplies those fields on read,
 * so the seed keeps exercising the migration path rather than short-circuiting
 * it. Hence the partial draft type + the single cast in surveysSeed().
 */
type SeedSurvey = Partial<SurveyDraft> &
  Pick<
    SurveyRecord,
    "id" | "owner" | "createdAt" | "updatedAt" | "syncState" | "syncedAt" | "rev"
  >;

/**
 * Survey seed — exact port of app/survey.js seedData() (rss_surveys_v4).
 * One record per lifecycle stage: requested → scheduled → onsite → completed.
 * Relative dates are computed at call time.
 */
export function surveysSeed(): SurveyRecord[] {
  const DAY = 86400000;
  const now = Date.now();
  const ago = (d: number) => now - d * DAY;

  // Site Intake extension defaults (IDEAS #45) — the prototype fixtures
  // predate the tiered intake, so every seed record starts blank there.
  const intake = () => ({
    auditoriumSize: "",
    yearBuilt: "",
    systemsState: blankSystemsState(),
    disciplines: {},
    disciplinesActive: [],
    inventory: [],
    intakeReady: false,
    // #34: these fixtures predate the lead thread — no lead/visit link.
    leadId: null,
    visitId: null,
  });

  const rows: SeedSurvey[] = [
    // 1) REQUESTED — office brief filled, awaiting scheduling
    {
      id: "FS-1055",
      ...intake(),
      customer: "Lakeside Community Church",
      customerId: "lakeside",
      locationId: "lc1",
      venue: "Sanctuary",
      venueType: "Worship / sanctuary",
      address: "2551 Jackson St, Oshkosh, WI 54901",
      contact: "Pastor Liam Boyd",
      contactPhone: "(920) 555-0198",
      contactEmail: "liam@lakesidechurch.org",
      visitType: "Budgetary walk-through",
      reason: "New sanctuary build-out — stage lighting + a simple fly for banners.",
      travelTime: "52 min",
      distance: "41 mi",
      hasBOM: false,
      hasDrawings: true,
      hasPhotos: false,
      quoteNeededBy: "2026-08-05",
      budgetary: true,
      projectCompletion: "2026-12-01",
      installTimeframe: "6–12 months",
      loadingDock: "",
      elevatorSize: "",
      floorType: "",
      accessDoorSize: "",
      liftNeeded: "",
      liftSupplier: "",
      scopeOfWork: "",
      quoteLook:
        "Single budgetary number with a short scope narrative — going to a building committee.",
      notes: "",
      measurements: {},
      conditions: [],
      photos: [],
      stage: "requested",
      assignedTo: "",
      scheduledDate: "",
      requestedBy: "Jeff Chesebro",
      requestedAt: ago(0),
      owner: "Jeff Chesebro",
      createdAt: ago(0),
      updatedAt: ago(0),
      syncState: "pending",
      syncedAt: null,
      rev: 1,
    },
    // 2) SCHEDULED — assigned + dated, not yet visited
    {
      id: "FS-1053",
      ...intake(),
      customer: "North Ridge High School",
      customerId: "northridge",
      locationId: "nr1",
      venue: "Main Auditorium",
      venueType: "Proscenium theater",
      address: "1515 E Newberry St, Appleton, WI 54915",
      contact: "Greg Salas",
      contactPhone: "(920) 555-0176",
      contactEmail: "gsalas@northridgehs.edu",
      visitType: "Design verification",
      reason:
        "Verify measured drawings against as-built before we release the counterweight quote.",
      travelTime: "1 hr 5 min",
      distance: "58 mi",
      hasBOM: true,
      hasDrawings: true,
      hasPhotos: true,
      quoteNeededBy: "2026-07-18",
      budgetary: false,
      projectCompletion: "2026-09-30",
      installTimeframe: "1–3 months",
      loadingDock: "",
      elevatorSize: "",
      floorType: "",
      accessDoorSize: "",
      liftNeeded: "",
      liftSupplier: "",
      scopeOfWork:
        "Add 6 line sets and replace worn purchase lines. Verify existing head block sizing.",
      quoteLook:
        "Full itemized quote, school district PO format, alternates listed separately.",
      notes: "Summer install window only.",
      measurements: {},
      conditions: [],
      photos: [],
      stage: "scheduled",
      assignedTo: "Nic Trapani",
      scheduledDate: "2026-07-06",
      requestedBy: "Jeff Chesebro",
      requestedAt: ago(3),
      owner: "Nic Trapani",
      createdAt: ago(3),
      updatedAt: ago(1),
      syncState: "synced",
      syncedAt: ago(1),
      rev: 2,
    },
    // 3) ON-SITE — assigned to me, capture in progress
    {
      id: "FS-1054",
      ...intake(),
      customer: "Badger Ballet Company",
      customerId: "badger",
      locationId: "bb1",
      venue: "Main Stage",
      venueType: "Proscenium theater",
      address: "2201 Atwood Ave, Madison, WI 53704",
      contact: "Priya Anand",
      contactPhone: "(608) 555-0121",
      contactEmail: "priya@badgerballet.org",
      visitType: "Initial site survey",
      reason:
        "Replace end-of-life counterweight system; add a handful of motorized line sets.",
      travelTime: "1 hr 20 min",
      distance: "78 mi",
      hasBOM: false,
      hasDrawings: false,
      hasPhotos: false,
      quoteNeededBy: "2026-07-30",
      budgetary: false,
      projectCompletion: "2026-11-15",
      installTimeframe: "3–6 months",
      loadingDock: "Dock-height, rear alley",
      elevatorSize: "None to stage",
      floorType: "Wood / sprung",
      accessDoorSize: "7' × 8' scene dock",
      liftNeeded: "Scissor lift",
      liftSupplier: "We supply",
      scopeOfWork: "Full counterweight replacement; 4 motorized sets on the electrics.",
      quoteLook: "",
      notes: "Capturing today — grid access via the SL gallery ladder.",
      measurements: {
        proW: `38'-0"`,
        proH: `22'-0"`,
        stageDepth: `26'-0"`,
        gridH: "48'",
        wingSL: "10'",
        wingSR: "11'",
      },
      conditions: ["Existing rigging — counterweight", "Limited load-in access"],
      photos: [],
      stage: "onsite",
      assignedTo: "Jeff Chesebro",
      scheduledDate: "2026-07-01",
      requestedBy: "Nic Trapani",
      requestedAt: ago(5),
      owner: "Jeff Chesebro",
      createdAt: ago(5),
      updatedAt: ago(0),
      syncState: "pending",
      syncedAt: null,
      rev: 4,
    },
    // 4) COMPLETED — fully captured, ready to quote
    {
      id: "FS-1042",
      ...intake(),
      customer: "Lakefront Performing Arts Center",
      customerId: "lakefront",
      locationId: "lf1",
      venue: "Main Hall",
      venueType: "Proscenium theater",
      address: "929 N Water St, Milwaukee, WI 53202",
      contact: "Dana Whitlock",
      contactPhone: "(414) 555-0142",
      contactEmail: "dwhitlock@lakefrontpac.org",
      visitType: "Initial site survey",
      reason: "Full rigging replacement — failing hemp system, insurance flagged.",
      travelTime: "35 min",
      distance: "22 mi",
      hasBOM: false,
      hasDrawings: true,
      hasPhotos: true,
      quoteNeededBy: "2026-07-24",
      budgetary: false,
      projectCompletion: "2026-10-15",
      installTimeframe: "3–6 months",
      loadingDock: "Grade-level, alley off Water St",
      elevatorSize: "None to stage",
      floorType: "Wood / sprung",
      accessDoorSize: "6' × 9' scene dock",
      liftNeeded: "Scissor lift",
      liftSupplier: "We supply",
      scopeOfWork:
        "Remove existing hemp system; install 32-line counterweight system with loading gallery. Reuse existing pin rail location if structure allows.",
      quoteLook:
        "Itemized by line set + rigging hardware, labor broken out separately. Include engineering allowance.",
      notes:
        "Hemp house, no purchase line. Load-in is up a half-flight from the alley — confirm motorized assist. GC wants abatement cleared before we survey the gridiron.",
      measurements: {
        proW: `42'-0"`,
        proH: `24'-6"`,
        stageDepth: `31'-0"`,
        apron: `5'-6"`,
        wingSR: `14'-0"`,
        wingSL: `12'-0"`,
        houseR: "22'",
        houseL: "22'",
        steelH: "58'",
        roofH: "62'",
        gridH: `54'-0"`,
        pitDepth: `8'-0"`,
        stageH: `3'-6"`,
        houseH: "34'",
        beam1SRDist: `6'-0"`,
        beamSpacing: "24'",
        beamDirection: "Runs US–DS (up/down-stage)",
        beamType: "I-beam",
        drawSide: "Stage right",
        rigType: "Hemp",
        foh1Dist: "18'",
        foh1Trim: "26'",
        foh2Dist: "34'",
        foh2Trim: "28'",
        tormDist: "24'",
        tormTrim: "22'",
      },
      conditions: [
        "Existing rigging — hemp",
        "Limited load-in access",
        "Asbestos / hazmat unknown",
        "Historic / preservation constraints",
      ],
      photos: [],
      stage: "completed",
      assignedTo: "Nic Trapani",
      scheduledDate: "2026-06-28",
      requestedBy: "Jeff Chesebro",
      requestedAt: ago(8),
      owner: "Nic Trapani",
      createdAt: ago(8),
      updatedAt: ago(2),
      syncState: "synced",
      syncedAt: ago(2),
      rev: 5,
    },
  ];
  return rows as SurveyRecord[];
}
